### PR TITLE
DS-452: Upgrade to Node 20

### PR DESCRIPTION
**Pull request by stfurkan**
# READY FOR REVIEW

# Summary
- Upgrade to Node 20

# Review By (Date)
- End of sprint

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. Open another project that we use this package (e.g. `ood-givegab-portal`) and remove the package `npm uninstall weblogin-auth-sdk`
2. Install the upgraded package (this branch) to the other project `npm install "https://github.com/SU-SWS/weblogin-auth-sdk.git#task/DS-452_upgrade-node-20" --save`
3. Make sure that auth functions works as expected

### CODE REVIEW

**Comment by stfurkan** [comment]
@sherakama I also tested this in this PR --> https://github.com/SU-SWS/ood-givegab-portal/pull/108
FYI

**Comment by sherakama** [comment]
@stfurkan, Can we update the packages here too, please. We don't need major or minor versions but I'd like to see the patch versions bumped as well as letting the package manager do its dependency thing while running on node 20.

**Comment by stfurkan** [comment]
@sherakama I made the patch version updates

**Comment by stfurkan** [comment]
> GTG. Thank you.

Thanks for the review @sherakama :)

**Pull request merged**
